### ISSUE TITLE
Error: no mixin named input-placeholder

### ISSUE THREAD

**Issue by lvl99** [Igosuki/compass-mixins#83]
Perhaps the Compass mixin files in this repo are now out of date with existing Compass mixins?

I took the mixin `input-placeholder` from Compass and put it in my own file and it then complains about:

`Error: no mixin named with-each-prefix`

**Comment by shri3k** [comment]
It looks like it. I tried including `input-placeholder` which was in `_user-interface.scss` from Compass which also includes `_support.scss` instead of `_shared.scss`. I took the whole `_support.scss` from Compass again (because it was giving me the same error as the one you mentioned) and replaced with it and I found out that `_shared.scss` actually relied on some of ruby's "monkey-patched" functions from https://github.com/Compass/compass/blob/stable/core/lib/compass/core/sass_extensions/functions/cross_browser_support.rb#L173-L182
```rb
# The percent of users relying on a particular prefix
  def prefix_usage(prefix, capability, capability_options)
    assert_type prefix, :String
    assert_type capability, :String
    number(Compass::Core::CanIUse.instance.prefixed_usage(prefix.value,
                                                    capability.value,
                                                    unbox_capability_options_list(capability_options)))
  rescue ArgumentError => e
    raise Sass::SyntaxError.new(e.message)
  end
  declare(:prefix_usage, [:prefix, :capability])
```
I'm not familiar with ruby but I agree some of the mixins here could use some updating.

**Comment by xzyfer** [comment]
The `input-placeholder` mixin has been added in v0.12.9.
